### ISSUE TITLE
Dockerfile to Support Ease of Installation for Raspberry Pi

### ISSUE THREAD

**Issue by WilliamAlexanderMorrison** [bendikwa/igrill#13]
First, thank you SO much for providing this fork and the troubleshooting information! I got my implementation working like I want, and in that process created a dockerfile and a docker-compose file that might help standardize the install for novice users (like myself). I believe I have the docker-compose configured correctly such that if the monitor script ever exits with an error, the container will be restarted to try again.

I had a specific use case I wrote up the documentation for here, https://github.com/WilliamAlexanderMorrison/igrill-hassio. To be totally frank, I don't have the know-how to do any sort of testing outside of my use-case on the raspberry pi, but the docker container should make things standardized across devices. 

Do you have interest in me submitting a PR to add a docker directory with the docker files and some documentation to the readme?

Thanks again,

-Will

**Comment by bendikwa** [comment]
Hi

Thank you for contributing.
Yes a docker setup / example is a good Idea to include in the project, and a PR would be most welcome!

-Bendik

**Comment by bendikwa** [comment]
I have added a Dockerfile, and a folder for example scripts. If you would like, a PR with your docker-compose.yaml and an explanation in the README would be excellent.
