### ISSUE TITLE
Pulse 2000 compatible

### ISSUE THREAD

**Issue by PaulAntonDeen** [bendikwa/igrill#14]
Awesome work, thank!
I have a Weber Pulse 2000 electric grill which has the temp probes built in. What data do I need to capture from my grill to integrate it in this code and make it work?

**Comment by runestone74** [comment]
If you have an Android device you can scan for UUID codes with this app https://play.google.com/store/apps/details?id=com.macdom.ble.blescanner

**Comment by runestone74** [comment]
My guess is that these two (or one) lines is needed for the internal temperature probe in igrill.py
#Pulse 1000
PROBE5_TEMPERATURE = btle.UUID('06ef000A-2e06-4b79-9e33-fce2c42805ec')
PROBE5_THRESHOLD   = btle.UUID('06ef000B-2e06-4b79-9e33-fce2c42805ec')

#Pulse 2000? havent seen these actual values, just an educated guess with C and D
PROBE6_TEMPERATURE = btle.UUID('06ef000C-2e06-4b79-9e33-fce2c42805ec')
PROBE7_THRESHOLD   = btle.UUID('06ef000D-2e06-4b79-9e33-fce2c42805ec')

**Comment by PaulAntonDeen** [comment]
Thanks for the tip. I tried it but could not see the BBQ with that app (tried it with and without being connected to the bbq in the app). What did you base these UUID assumptions on?

Since the bbq is mains connected it could be that it does not support BLE but is using a less energy efficient protocol. It could also be that I just don't know how to work this app yet so I'll keep trying. I might also be able to just put raspbian on my pi 3b+ and start scanning from there.

**Comment by PaulAntonDeen** [comment]
Using gatttool with command primary I get these services listed:
`
attr handle: 0x0001, end grp handle: 0x0003 uuid: 00001801-0000-1000-8000-00805f9b34fb
attr handle: 0x0010, end grp handle: 0x0014 uuid: 00001800-0000-1000-8000-00805f9b34fb
attr handle: 0x0015, end grp handle: 0x001d uuid: 0000180a-0000-1000-8000-00805f9b34fb
attr handle: 0x0020, end grp handle: 0x002f uuid: 64ac0000-4a4b-4b58-9f37-94d3c52ffdf7
attr handle: 0x0030, end grp handle: 0x004b uuid: 7e920000-68dc-41c7-943f-518b278cea88
attr handle: 0x0080, end grp handle: 0x0083 uuid: 0000180f-0000-1000-8000-00805f9b34fb
attr handle: 0x0090, end grp handle: 0x00b3 uuid: 6c910000-58dc-41c7-943f-518b278ceaaa
`
and characteristics spits out:
`
handle: 0x0002, char properties: 0x10, char value handle: 0x0003, uuid: 00002a05-0000-1000-8000-00805f9b34fb
handle: 0x0011, char properties: 0x02, char value handle: 0x0016, uuid: 00002a00-0000-1000-8000-00805f9b34fb
handle: 0x0013, char properties: 0x02, char value handle: 0x0018, uuid: 00002a01-0000-1000-8000-00805f9b34fb
handle: 0x0016, char properties: 0x02, char value handle: 0x0017, uuid: 00002a24-0000-1000-8000-00805f9b34fb
handle: 0x0018, char properties: 0x02, char value handle: 0x0019, uuid: 00002a25-0000-1000-8000-00805f9b34fb
handle: 0x001a, char properties: 0x02, char value handle: 0x001b, uuid: 00002a29-0000-1000-8000-00805f9b34fb
handle: 0x001c, char properties: 0x02, char value handle: 0x001d, uuid: 00002a27-0000-1000-8000-00805f9b34fb
handle: 0x0021, char properties: 0x02, char value handle: 0x0022, uuid: 64ac0001-4a4b-4b58-9f37-94d3c52ffdf7
handle: 0x0023, char properties: 0x08, char value handle: 0x0024, uuid: 64ac0002-4a4b-4b58-9f37-94d3c52ffdf7
handle: 0x0025, char properties: 0x02, char value handle: 0x0026, uuid: 64ac0003-4a4b-4b58-9f37-94d3c52ffdf7
handle: 0x0027, char properties: 0x08, char value handle: 0x0028, uuid: 64ac0004-4a4b-4b58-9f37-94d3c52ffdf7
handle: 0x0029, char properties: 0x08, char value handle: 0x002a, uuid: 64ac0005-4a4b-4b58-9f37-94d3c52ffdf7
handle: 0x002b, char properties: 0x02, char value handle: 0x002c, uuid: 64ac0006-4a4b-4b58-9f37-94d3c52ffdf7
handle: 0x002d, char properties: 0x12, char value handle: 0x002e, uuid: 64ac0007-4a4b-4b58-9f37-94d3c52ffdf7
handle: 0x0031, char properties: 0x0a, char value handle: 0x0032, uuid: 06ef0001-2e06-4b79-9e33-fce2c42805ec
handle: 0x0033, char properties: 0x12, char value handle: 0x0034, uuid: 06ef0002-2e06-4b79-9e33-fce2c42805ec
handle: 0x0036, char properties: 0x0a, char value handle: 0x0037, uuid: 06ef0003-2e06-4b79-9e33-fce2c42805ec
handle: 0x0038, char properties: 0x12, char value handle: 0x0039, uuid: 06ef0004-2e06-4b79-9e33-fce2c42805ec
handle: 0x003b, char properties: 0x0a, char value handle: 0x003c, uuid: 06ef0005-2e06-4b79-9e33-fce2c42805ec
handle: 0x003d, char properties: 0x12, char value handle: 0x003e, uuid: 06ef0006-2e06-4b79-9e33-fce2c42805ec
handle: 0x0040, char properties: 0x0a, char value handle: 0x0041, uuid: 06ef0007-2e06-4b79-9e33-fce2c42805ec
handle: 0x0042, char properties: 0x12, char value handle: 0x0043, uuid: 06ef0008-2e06-4b79-9e33-fce2c42805ec
handle: 0x0045, char properties: 0x0a, char value handle: 0x0046, uuid: 06ef0009-2e06-4b79-9e33-fce2c42805ec
handle: 0x0047, char properties: 0x12, char value handle: 0x0048, uuid: 06ef000a-2e06-4b79-9e33-fce2c42805ec
handle: 0x004a, char properties: 0x0a, char value handle: 0x004b, uuid: 06ef000b-2e06-4b79-9e33-fce2c42805ec
handle: 0x0081, char properties: 0x12, char value handle: 0x0082, uuid: 00002a19-0000-1000-8000-00805f9b34fb
handle: 0x0091, char properties: 0x12, char value handle: 0x0092, uuid: 6c910001-58dc-41c7-943f-518b278ceaaa
handle: 0x0094, char properties: 0x0a, char value handle: 0x0095, uuid: 6c910002-58dc-41c7-943f-518b278ceaaa
handle: 0x0097, char properties: 0x02, char value handle: 0x0098, uuid: 6c910003-58dc-41c7-943f-518b278ceaaa
handle: 0x009b, char properties: 0x0a, char value handle: 0x009c, uuid: 6c910004-58dc-41c7-943f-518b278ceaaa
handle: 0x009e, char properties: 0x12, char value handle: 0x009f, uuid: 6c910005-58dc-41c7-943f-518b278ceaaa
handle: 0x00a1, char properties: 0x12, char value handle: 0x00a2, uuid: 6c910006-58dc-41c7-943f-518b278ceaaa
handle: 0x00a5, char properties: 0x12, char value handle: 0x00a6, uuid: 6c910007-58dc-41c7-943f-518b278ceaaa
handle: 0x00a8, char properties: 0x12, char value handle: 0x00a9, uuid: 6c910008-58dc-41c7-943f-518b278ceaaa
handle: 0x00ab, char properties: 0x0a, char value handle: 0x00ac, uuid: 6c910009-58dc-41c7-943f-518b278ceaaa
handle: 0x00af, char properties: 0x0a, char value handle: 0x00b0, uuid: 6c91000a-58dc-41c7-943f-518b278ceaaa
handle: 0x00b2, char properties: 0x0a, char value handle: 0x00b3, uuid: 6c91000b-58dc-41c7-943f-518b278ceaaa
`

**Comment by PaulAntonDeen** [comment]
The 4 probes are the same UUID as the standard igrill.

The main heating element temperatures and setpoint are communicated on UUID 6c91000a-58dc-41c7-943f-518b278ceaaa. The return example is 20 30 32 30 20 30 31 35 20 30 30 30 20 30 30 30 which can be converted HextoASCII into "020 015 000 000" which can be read as actual temp left element, right element. Temp setpoint left right.

Authentication is not working and thus I cannot read the probe temperatures so I need to figure out how to debug that, any tips?

**Comment by bendikwa** [comment]
Hi
It would be cool to be able to support the pulse 2000, unfortunately, I don’t think I can help much. The original authentication code is from the first fork, https://github.com/onlywade/igrill and the updated authentication method was contributed by kins-dev: https://blog.kins.dev/2019/04/igrill-device-support-for-igrill-smoker.html
So other than turning the debug logging on, and trying to see where it fails, I don’t have any good ideas.

**Comment by PaulAntonDeen** [comment]
Yeah I'm not experienced with Python so I'm figuring it out as I go through here. It gets stuck after sending key of all 0's (that is a message with debug on). It just never moves past that. The code i'm using for now is just exactly your code with this for the device.yaml:

`
devices:
  - name:       'Pulse2000'                  # Unique name of the device
    type:       'igrill_v3'              # Supported devices: igrill_mini, igri$
    address:    '70:91:8F:7B:1A:6C'      # The MAC of the device
    topic:      'temperature/outside'    # The topic to publish on. will have n$
    interval:   20                       # Polling interval
`

 Can you help modify the code to check the extra UUID for the central heating zones actual temperature and setpoints? Also if we specify the pulse device we can disable the battery check.

I have ordered a BLE sniffer (Adafruit Bluefruit) so maybe I can use that to figure out the authentication method.

**Comment by bendikwa** [comment]
That sound like the same issue as "Getting stuck at authenticating"

Have you tried to use bluetoothctl to pair the iGrill first?
Or the trick in the readme: https://github.com/bendikwa/igrill#troubleshooting

**Comment by PaulAntonDeen** [comment]
Commenting out that line in the udev rules fixed the authentication, now to figure out how to read that main temperature :)

**Comment by PaulAntonDeen** [comment]
Got it to work :)
I will work on prettying up the code and then create a pull request

**Comment by PaulAntonDeen** [comment]
Pull request  #16

**Comment by bendikwa** [comment]
I have merged the PR to https://github.com/bendikwa/igrill/tree/pulse2000_support and refactored the code a bit. Can you test to see that it still works?

Does the Pulse 2000 have a battery indicator? Or should we remove that?

-Bendik

**Comment by PaulAntonDeen** [comment]
That code looks much nicer, thanks :)
It does not have a battery but will report 100% whenever read, so it is safe to read. Just ignore it on the MQTT sensor level in HA.
I will test it out today.

**Comment by PaulAntonDeen** [comment]
Tested, working great!
You want to add this to the readme as an example of how to add the sensors in Home Assistant:

`
sensor:
  - platform: mqtt
  state_topic: "temperature/outside/Pulse 2000/probe1"
  name: "P2000 Probe 1"
  qos: 0
  unit_of_measurement: "ºC"
- platform: mqtt
  state_topic: "temperature/outside/Pulse 2000/probe2"
  name: "P2000 Probe 2"
  qos: 0
  unit_of_measurement: "ºC"
- platform: mqtt
  state_topic: "temperature/outside/Pulse 2000/probe3"
  name: "P2000 Probe 3"
  qos: 0
  unit_of_measurement: "ºC"
- platform: mqtt
  state_topic: "temperature/outside/Pulse 2000/probe4"
  name: "P2000 Probe 4"
  qos: 0
  unit_of_measurement: "ºC"
- platform: mqtt
  state_topic: "temperature/outside/Pulse 2000/heating_element"
  name: "P2000 Heating element"
  qos: 0
  
- platform: template
  sensors:
    p2000_left_element_actual:
      value_template: "{{ states('sensor.p2000_heating_element').split(' ')[1]|int}}"
      unit_of_measurement: 'ºC'
      icon_template: mdi:grill
    p2000_right_element_actual:
      value_template: "{{ states('sensor.p2000_heating_element').split(' ')[2]|int}}"
      unit_of_measurement: 'ºC'
      icon_template: mdi:grill
    p2000_left_element_setpoint:
      value_template: "{{ states('sensor.p2000_heating_element').split(' ')[3]|int}}"
      unit_of_measurement: 'ºC'
      icon_template: mdi:grill
    p2000_right_element_setpoint:
      value_template: "{{ states('sensor.p2000_heating_element').split(' ')[4]|int}}"
      unit_of_measurement: 'ºC'
      icon_template: mdi:grill
`

**Comment by PaulAntonDeen** [comment]
On a seperate thought, since it only publishes a probe temp when it is connected it means that the non-connected probe's stay at the temperature they had the last time they were connected making it harder to see which are reporting. Should we tweak the temp reporting from the probes to just send a 0 or . when the 65356 value is read from the probes?

**Comment by bendikwa** [comment]
Great! I'll merge the Pulse 2000 support to master.

Regarding your two other suggestions: 

1. I think that the Home Assistant information belongs in the [Home Assistant forum](https://community.home-assistant.io/t/weber-igrill-2-integration-with-lovelace-ui/61880). I dont actually use  Home Assistant, so I will not be able to help with it. ;-)

2. On the subject of non-connected probes, I guess it is the same as https://github.com/bendikwa/igrill/issues/6 ? I have actually just pushed an attempt on a fix for this to a branch, hope to get it merged to master today.

**Comment by bendikwa** [comment]
Merged to master
