### ISSUE TITLE
external mqtt server not working

### ISSUE THREAD

**Issue by bertdeelman** [bendikwa/igrill#15]
Hi,

I want to use an external mqtt server. But the config did not accept it. It is always using localhost instead of the external mqtt broker. 

I edit the utils.py file and changes the line of code from "localhost" to "ip-adress-external-mqtt-server". Now it is working. 

`config_defaults = {
    'mqtt': {
        'host': '**ip-adress-external-mqtt-server**'
    }
}`

Regards,
Bert

**Comment by PaulAntonDeen** [comment]
Did you edit the mqtt.yaml file in the exampleconfig directory?

**Comment by bertdeelman** [comment]
Yes, I did.

**Comment by bendikwa** [comment]
Hi
Can you post your config file? And the command you are using to start the monitor script?

**Comment by bertdeelman** [comment]
Hi,

I did a fresh install and followed the instructions. Made a config/ directory and edit the .yaml files. At the mwqtt file a change the host from localhost to media4.local. 

```
2020-04-27 18:45:57,814 MainThread DEBUG: YAML LOAD: {'devices': [{'topic': 'cooking/grill', 'interval': 20, 'type': 'igrill_v2', 'name': 'monolith', 'address': '70:91:8F:07:4E:C2'}]}
2020-04-27 18:45:57,923 MainThread DEBUG: YAML LOAD: {'host': 'media4.local'}
2020-04-27 18:45:57,931 MainThread DEBUG: Validating dict {'mqtt': {'host': 'localhost'}, 'devices': [{'topic': 'cooking/grill', 'interval': 20, 'type': 'igrill_v2', 'name': 'monolith', 'address': 'XX:XX:XX:XX:4E:C2'}]} with specs: {'required_entries': {'mqtt': <type 'dict'>, 'devices': <type 'list'>}}
```
socket.error: [Errno 111] Connection refused. May be at the validating dict part? I should expect the the external mqtt server instead of localhost.

command: ./monitor.py -c config

Regards,
Bert

**Comment by bendikwa** [comment]
It looks like your mqtt config is missing a leadig "mqtt" key:
```
mqtt:
  host:       'mqtt.example.com'
```

The config loader does not look at the filenames, it just loads all config files in the given directory.
The device/mqtt file splitt is just for organizing your config. You can put everything in one file.

-Bendik

**Comment by bertdeelman** [comment]
Hi Bendik,

Aha, that did the trick. Thanks.

**Comment by bendikwa** [comment]
Added a comment to try to make it clear how to change the config.
https://github.com/bendikwa/igrill/commit/ce3ca7a09f3a1918142ba2f46f952938dd0c6d03
