### ISSUE TITLE
iGrill won't connect

### ISSUE THREAD

**Issue by Exit2Studios** [bendikwa/igrill#18]
I had everything working fine, and now my iGrill v2 is in an endless loop of connecting/disconnecting.  I've followed the troubleshooting steps and that didn't resolve it.

pi@raspberrypi:~ $ bluetoothctl
Agent registered
[CHG] Device 70:91:8F:11:FF:F5 Connected: yes
[CHG] Device 70:91:8F:11:FF:F5 Connected: no
[CHG] Device 70:91:8F:11:FF:F5 Connected: yes
[CHG] Device 70:91:8F:11:FF:F5 Connected: no
[CHG] Device 70:91:8F:11:FF:F5 Connected: yes
[CHG] Device 70:91:8F:11:FF:F5 Connected: no
[CHG] Device 70:91:8F:11:FF:F5 Connected: yes
[CHG] Device 70:91:8F:11:FF:F5 Connected: no
[CHG] Device 70:91:8F:11:FF:F5 Connected: yes
[CHG] Device 70:91:8F:11:FF:F5 Connected: no
[CHG] Device 70:91:8F:11:FF:F5 Connected: yes
[CHG] Device 70:91:8F:11:FF:F5 Connected: no
[CHG] Device 70:91:8F:11:FF:F5 Connected: yes
[CHG] Device 70:91:8F:11:FF:F5 Connected: no
[CHG] Device 70:91:8F:11:FF:F5 Connected: yes
[CHG] Device 70:91:8F:11:FF:F5 Connected: no
[CHG] Device 70:91:8F:11:FF:F5 Connected: yes
[CHG] Device 70:91:8F:11:FF:F5 Connected: no
[CHG] Device 70:91:8F:11:FF:F5 Connected: yes
[CHG] Device 70:91:8F:11:FF:F5 Connected: no
[CHG] Device 70:91:8F:11:FF:F5 Connected: yes
[CHG] Device 70:91:8F:11:FF:F5 Connected: no
[CHG] Device 70:91:8F:11:FF:F5 Connected: yes
[CHG] Device 70:91:8F:11:FF:F5 Connected: no
[CHG] Device 70:91:8F:11:FF:F5 Connected: yes
[CHG] Device 70:91:8F:11:FF:F5 Connected: no
[bluetooth]#

**Comment by bendikwa** [comment]
I have not seen this behavior before. Does the iGrill work with the official app?

**Comment by Exit2Studios** [comment]
Yes, works on the app and was working via MQTT as well as Home Assistant for a short time, but now won't stay connected.

**Comment by bendikwa** [comment]
Do you see this even without the ./monitor.py script running?

Anyway, I would try with a fresh install and/or a different raspberry pi.

**Comment by Exit2Studios** [comment]
I am using a Pi Zero W for this...would that be an issue in any way?

**Comment by Exit2Studios** [comment]
I reinstalled (twice) and now have bluetooth working.  However I'm having MQTT issues.  Get the following:

pi@raspberrypi:~/igrill $ ./monitor.py
2020-05-07 19:26:40,609 MainThread INFO: log_level set to: INFO
Traceback (most recent call last):
  File "./monitor.py", line 58, in <module>
    main()
  File "./monitor.py", line 39, in main
    devices = get_device_threads(config.get_config('devices'), config.get_config('mqtt'), run_event)
  File "/home/pi/igrill/utils.py", line 131, in get_device_threads
    enumerate(device_config)]
  File "/home/pi/igrill/igrill.py", line 201, in __init__
    self.mqtt_client = utils.mqtt_init(mqtt_config)
  File "/home/pi/igrill/utils.py", line 97, in mqtt_init
    mqtt_client.connect(**strip_config(mqtt_config, ['host', 'port', 'keepalive']))
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

**Comment by bendikwa** [comment]
`socket.error: [Errno 111] Connection refused` normally happens when mqtt host/port is incorrect.
Are you sure he correct config is loaded?
If you start with `pi@raspberrypi:~/igrill $ ./monitor.py -l DEBUG` the loaded config should be logged.

**Comment by Exit2Studios** [comment]
So what's strange, is I plugged in a monitor/keyboard and connected to the device via the desktop.  While connected I get the following when running the above command:

`2020-05-08 16:09:50,606 igrill DEBUG: Device thread igrill (re)started, trying to connect to iGrill with address: 70:91:8F:11:FF:F5
2020-05-08 16:09:50,640 igrill DEBUG: Created new device with name igrill
2020-05-08 16:09:50,642 igrill DEBUG: Trying to connect to the device with address 70:91:8F:11:FF:F5
2020-05-08 16:09:50,647 igrill DEBUG: Calling btle.Peripheral.__init__ with lock: 3066492160
2020-05-08 16:09:50,798 igrill DEBUG: Failed to connect to peripheral 70:91:8F:11:FF:F5, addr type: public
2020-05-08 16:09:50,801 igrill DEBUG: Sleeping for 20 seconds before retrying
`

**Comment by bendikwa** [comment]
Looks like the same issue as https://github.com/bendikwa/igrill/issues/20
trying to connect, and immediately fails.
To me it looks like the device is in a bad state, and a reconnect does not help.

Hard to figure out without being able to reproduce.

Can you try my suggestions in the other issue?

-Bendik

**Comment by Exit2Studios** [comment]
I did all of the steps mentioned in the other issue.  I power cycled the igrill after running monitor.py and got to this point:

2020-05-08 22:46:39,012 igrill DEBUG: Device thread igrill (re)started, trying to connect to iGrill with address: 70:91:8F:11:FF:F5
2020-05-08 22:46:39,016 igrill DEBUG: Created new device with name igrill
2020-05-08 22:46:39,019 igrill DEBUG: Trying to connect to the device with address 70:91:8F:11:FF:F5
2020-05-08 22:46:39,022 igrill DEBUG: Calling btle.Peripheral.__init__ with lock: 3066815744
2020-05-08 22:46:39,509 igrill DEBUG: Releasing lock: 3066815744
2020-05-08 22:46:41,867 igrill DEBUG: Authenticating...
2020-05-08 22:46:41,870 igrill DEBUG: Sending key of all 0's

I commented out the line in /lib/udev/rules.d/90-pi-bluetooth.rules as well and it's still freezing at the "sending key of all 0's"

Also, isn't it strange that the iGrill has a solid blue light, appears to be connected to the pi, but won't connect to the monitor?  

When I do bluetoothctl, I get 
Agent registered
[iGrill_V202-FFF5]#

**Comment by bendikwa** [comment]
Does it have a sold light even if the pi is not connected? (E.g. powered off)
Can there be another device, like a tablet, or another phone "stealing" the connection?

I run a igrill_v3 and a igrill_mini on a raspberry pi3, and have not had any of these problems, and since I dont have the devices you are using, and to be honest, don't have a lot of experience doing Bluetooth device programming, it is hard for me to help. The next step for me would be to start digging into system logs on the PI to see if there are some clues there.

**Comment by Exit2Studios** [comment]
The solid light blinks if the pi is shutdown. So it appears to be connected to the pi, but somehow the igrill app is unable to connect. I’m totally clueless as to what to do to troubleshoot it. Is there any reason why a pi zero would be a problem?  I don’t have an extra 3/4 at the moment to test.

**Comment by bendikwa** [comment]
Ref: https://github.com/bendikwa/igrill/issues/20#issuecomment-711132865
I dont have any other tips than to try to test without using the onboard Bluetooth and WiFi at the same time.
Sorry.

-Bendik
