### ISSUE TITLE
Enhancement Request - Home Assistant Add-on

### ISSUE THREAD

**Issue by war1000** [bendikwa/igrill#21]
Is it possible to get this as an Add-On to home assistant? Apologies, I do not know how to request it other than via issue.

**Comment by bendikwa** [comment]
Hi.
I honestly don't know, and as I am not using Home Assistant myself, this is not something that will be done by me. ;-)
Sorry.

-Bendik

**Comment by sanjay900** [comment]
i know its been a while, but i recently wrote this based on the code in this repo if you still need a home assistant addon
https://github.com/sanjay900/igrill
