### ISSUE TITLE
Multiple iGrill device connections not working correctly

### ISSUE THREAD

**Issue by volkerverkamp** [bendikwa/igrill#22]
It seems that communication to the MQTT server is not working correctly when using more than one iGrill device. In my setup I am using two iGrill Mini with iobroker MQTT adapter but after the initial successful publishing of both sensor's data only the data of one them (mostly the one switched on as latest) is being sent to the MQTT server.

I have checked the code and I think I found a solution (or workaround) by moving the MQTT client.reconnect() call into the while loop as follows:

`

    def run(self):
        while self.run_event.is_set():
            try:
                logging.debug("Device thread {} (re)started, trying to connect to iGrill with address: {}".format(self.name, self.address))
                device = self.device_types[self.type](self.address, self.name)
                while True:
                    self.mqtt_client.reconnect()
                    temperature = device.read_temperature(self.publish_missing_probes, self.missing_probe_value)
                    battery = device.read_battery()
                    heating_element = device.read_heating_elements()
                    utils.publish(temperature, battery, heating_element, self.mqtt_client, self.topic, device.name)
                    logging.debug("Published temp: {} and battery: {} to topic {}/{}".format(temperature, battery, self.topic, device.name))
                    logging.debug("Sleeping for {} seconds".format(self.interval))
                    time.sleep(self.interval)
            except Exception as e:
                logging.debug(e)
                logging.debug("Sleeping for {} seconds before retrying".format(self.interval))
                time.sleep(self.interval)

        logging.debug('Thread exiting')
`

**Comment by bendikwa** [comment]
I do not have this issue when I use multiple devices (one iGrill 3 and one mini), but I'll test your suggestion the next time I get the time to work on it.

-Bendik

**Comment by bendikwa** [comment]
This repository is no longer under active development, sorry.
