### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by meirkl** [bendikwa/igrill#23]
1. Is it possible to send commands to the iGrill device like the original app does? 
2. Does the iGrill device has some logic for turning on the alarm or the app sends the alarm command?
3. Is there a way to sniff the Bluetooth packets?

I want to build an app for controlling the iGrill through WiFi.

Thanks

**Comment by bendikwa** [comment]
1. Possible, probably, but it is way beyond my knowledge of both bluetooth and the Igrill, sorry.
2. See 1. ;-)
3. Probably, but I have never done it, you will probably have more luck searching for guides other places.

-Bendik

**Comment by meirkl** [comment]
Thanks!
