### ISSUE TITLE
Lighted knobs support?

### ISSUE THREAD

**Issue by netfriend85** [bendikwa/igrill#25]
My iGrill_V3 has a propane level sensor and lighted knobs control. 

The lighted knobs can be controlled by the iGrill app (on/off). Any chance of adding lighted knobs control support to the project? 
(I see the propane sensor enhancement is being addressed in #12)

Thanks for creating this great addition for the geeky iGrillers :-)

**Comment by bendikwa** [comment]
Hi
Thank you for reporting this, but I have no idea on how to do this, as my weber does not have the lighted knobs.
If you find out how to do this, you are welcome to post a PR. :-)

**Comment by sanjay900** [comment]
from what i can tell, sending a [1] to `EAEF0001-3909-454C-9D7E-E68CBA24A9B8` affects the led somehow, i suspect it toggles it?
If thats the case, i wonder what sending a [0] does
I don't own one of these to test
