### ISSUE TITLE
Docker image stopped working on Raspberry PI OS after full-upgrade

### ISSUE THREAD

**Issue by kneip68** [bendikwa/igrill#28]
Having updated docker last week, the container created about 1/2 year ago suddenly stopped working. The error message given was
`Error response from daemon: OCI runtime create failed: invalid mount {Destination:config Type:bind Source:/var/lib/docker/volumes/158dffded131a6cc3b65b19688ccd473e6c1435a0171928db808787dc7ea4e2a/_data Options:[rbind]}: mount destination config not absolute: unknown.`
I tried to rebuild the image first of all, which failed. I am running an updated Raspberry Pi OS 32bit on a RPi4, so was at first expecting this to be a side effect of the incompatibility of Alpine 3.13 with Raspberry Pi OS. 

So first thing I did was to update Dockerfile changing the FROM line to `FROM python:3-alpine3.12` which enabled me to rebuild, but the original error persisted when starting the container as per README.

So next I changed was the VOLUME line in Dockerfile to 
`VOLUME /usr/src/igrill/config`
and the CMD line to
`CMD [ "python", "./monitor.py", "-c", "/usr/src/igrill/config" ]`
now the container started and is working as expected (as it always has been).

Changes are available in fork kneip68/igrill and the completed image is at jheipmann/igrill in DockerHub.

Let me know whether I should send a pull request.

KR

Kneip

**Comment by bendikwa** [comment]
Hi.

A PR would be highly appreciated, thanks!

-Bendik

**Comment by kneip68** [comment]
Done

**Comment by bendikwa** [comment]
Fixed by https://github.com/bendikwa/igrill/pull/29

Thanks.
