### ISSUE TITLE
mqtt when using auth, username and password

### ISSUE THREAD

**Issue by rhamar** [bendikwa/igrill#5]
I ran into some problems with mqtt when using 'auth', 'username' and 'password' (Socket error on client 316c3c60-05fd-4b71-beb5-4c7d286fcdc6, disconnecting). When changing to anonymous and username and password are not necessary, it works. I use hass.io on my other pi and installed the add-on mosquitto broker. I'm already using mosquitto in combination with username and password with for example the shelly 1 switches with no problems at all. 

{
  "logins": [],
  "**anonymous": true**,
  "customize": {
    "active": false,
    "folder": "mosquitto"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}

**Comment by bendikwa** [comment]
My setup also uses auth with username and password. This works for me.
I dont know if setting '"anonymous": true' allows connections without TLS, but could it be a certificate error?

My mqtt broker (mosquitto) server uses a Letsencrypt cert.
Connecting to this broker works with this auth config for iGrill:
auth:
  username: <USERNAME>
  password: <PASSWORD>
tls:

Note the empty 'tls:' entry. This will initialize the paho-mqtt client with tls (using system trusted root certs)

**Comment by bendikwa** [comment]
I'm closing this due to it being over a year old. I'm guessing you got it working.
If not, please reopen the ticket.
