### ISSUE TITLE
changing probe, state of the entity is not changing to zero or to 'unknown'. 

### ISSUE THREAD

**Issue by rhamar** [bendikwa/igrill#6]
Another problem I have is when changing from probe, for example from 2 tot 3. The state of the entity is not changing to zero or to 'unknown'. The last measured temp on probe 2 is still showing.

<img width="755" alt="image" src="https://user-images.githubusercontent.com/46863494/53374633-23fa7580-3959-11e9-846d-7eaf0e1fa5cc.png">

**Comment by souhl** [comment]
My guess is that it just shows the last value received. (Wherever you display the values)
When a probe is just removed it should be the same, as only new values are shown. If the displaying entity is never receiving a „unknown“ value it won’t display it by its own. A solution might be to send one „unknown“ state message after a period of time not receiving new values from the probe.

**Comment by rhamar** [comment]
So what I found is that the MQTT client will not send information to the MQTT broker when no probe is connected. 

I did a little deep dive. 

igrill.py, line 153:
      _temps[probe_num] = float(temp) if float(temp) != 63536.0 else "False"_

/usr/local/lib/python2.7/dist-packages/paho/mqtt/publish.py, line 168:
      _payload : the payload to be published. If "" or None, a zero length payload will be published._

If you want the mqtt client to send a message with a payload with no probe connected, you should change line 153 into the following:
      _temps[probe_num] = float(temp) if float(temp) != 63536.0 else "None"_

And that did the trick (see screenshot). Now I have to modify Home Assistent so it can handle this value.

<img width="910" alt="image" src="https://user-images.githubusercontent.com/46863494/53680942-4fc38580-3ce2-11e9-91a4-c20ef85146d8.png">

To be continued

**Comment by bendikwa** [comment]
This was  by design when I implemented it.
I am not using Home Assistent for this project (I am using Prometheus/Grafana), and changing this would brake my setup, but I will consider making behaviour for disconnected probes configurable in a future release.

**Comment by bendikwa** [comment]
Better late than never: ;-)

I have added a new feature for this now:
Device config now takes 2 new optional flags.
```
publish_missing_probes: False                    # Optional default False - Enable sending a value for non-connected probes
missing_probe_value:    'missing'                # Optional default 'missing' - Value to send if publish_missing_probes is True
```

-Bendik

**Comment by PaulAntonDeen** [comment]
@rhamar did you ever figure out how to make HA handle the missing value in the mqtt sensor?

**Comment by PaulAntonDeen** [comment]
Works wonders! Tanks!
