### ISSUE TITLE
(Not) connected-Message

### ISSUE THREAD

**Issue by icinger** [bendikwa/igrill#9]
How about a "Connected" / "Disconnected"-MQTT-Message?

My iGrill sometimes disconnects from my Pi, it would be great to get some Info, if that happens.

**Comment by bendikwa** [comment]
Good idea, but with the current way of handling disconnected devices, this would require to keep this state separate. I am planning a rewrite of the device handling logic, and I will keep this in mind when doing it.

**Comment by bendikwa** [comment]
Sorry, I am no longer developing on this project.
